### ISSUE TITLE
Command errors should print actual command rather than template

### ISSUE THREAD

**Issue by bendrucker** [TakeScoop/kubectl-exec-forward#37]
When a command errors, the configuration is printed:

https://github.com/TakeScoop/kubectl-exec-forward/blob/981d22655715dddc1953b4957dc7f99be3903e3c/internal/command/command.go#L101-L103

What the user wants is to see the actual command that ran and failed, not the command template defined by the administrator.

**Comment by ryanwholey** [comment]
Yep, noticed this today when testing
