### ISSUE TITLE
Close forwarding connection when command completes

### ISSUE THREAD

**Issue by bendrucker** [TakeScoop/kubectl-exec-forward#40]
When the main command completes, the forwarding connection should be closed by default. An ideal command (e.g. `psql`) should block until work is complete and then exit 0. 

For commands that perform a side effect and then immediately exit 0, either the config or the user (CLI) could be allowed to specify that the connection should persist after the command.

**Comment by ryanwholey** [comment]
I've gone back and forth on this one. Our basic use case will probably be `open` which will require that the tunnel stays open. A change here would require that our users pass a flag each time. Not terrible, but still more flags for our target audience at Scoop

**Comment by bendrucker** [comment]
Sure, if folks want to use `open`, they can add boilerplate. The best experience will always be with `psql` and equivalents. You should be rewarded for picking Unix friendly tools. If you want to mix up command line and GUI such and all the associated problems (leaking connections), you should have to ask the program to leak that connection for you.
